/* (SYNC) */

/* (ASYNC) */
export const FETCH_CLIENTS_INIT = 'FETCH_CLIENTS_INIT';
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';
export const FETCH_CLIENTS_FAILURE = 'FETCH_CLIENTS_FAILURE';

export const FETCH_CLIENTS_SUCCESSMORE = 'FETCH_CLIENTS_SUCCESSMORE';
