/* (SYNC) */

export const ADD_CONTACT = 'ADD_CONTACT';
export const REMOVE_CONTACT = 'REMOVE_CONTACT';
export const CHANGE_CONTACT = 'CHANGE_CONTACT';
export const CHANGE_FORM = 'CHANGE_FORM';
/* (ASYNC) */
export const UPDATE_CLIENT_INIT = 'UPDATE_CLIENT_INIT';
export const UPDATE_CLIENT_SUCCESS = 'UPDATE_CLIENT_SUCCESS';
export const UPDATE_CLIENT_FAILURE = 'UPDATE_CLIENT_FAILURE';

export const FETCH_CLIENT_INIT = 'FETCH_CLIENT_INIT';
export const FETCH_CLIENT_SUCCESS = 'FETCH_CLIENT_SUCCESS';
export const FETCH_CLIENT_FAILURE = 'FETCH_CLIENT_FAILURE';
